repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--ignore-patterns=venv]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
    -   id: pygount
        name: pygount
        entry: pygount
        language: system
        types: [python]
        args: [--format=summary]
    -   id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        args: [-r]